#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var Promise, exec, uid, _module;
  Promise = require('bluebird');
  exec = require('shelljs').exec;
  uid = require('uid');
  _module = function(){
    var process, iface;
    process = function(block, opts){
      var defaultIsPng, targets;
      defaultIsPng = {
        cmd: function(block, tmpFile, tmpDir){
          block.to(tmpDir + "/" + tmpFile);
          return "ditaa " + tmpDir + "/" + tmpFile + " > /dev/null && cat " + tmpDir + "/" + tmpFile + ".png | base64";
        },
        output: function(tmpFile, tmpDir, output){
          return '\n <img class="exemd--diagram exemd--diagram__ditaa" src="data:image/png;base64,' + output + '" /> \n';
        }
      };
      targets = {
        'default': defaultIsPng,
        png: defaultIsPng
      };
      return opts.pluginTemplate(targets, block, opts);
    };
    iface = {
      process: process
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
